#!/bin/bash

grep -q clossed /proc/acpi/button/lid/LID0/state 
if [ $? = 0 ]
then
	## The laptop lid is clossed, Let's find out if it's plugged in.
	grep -q 0 /sys/class/power_supply/AC/online
	if [ $? = 0 ]
	then
		## The laptop is not plugged in. It should be asleep.
		pm-suspend
	fi
fi
